### ISSUE TITLE
Interested in project

### ISSUE THREAD

**Issue by ALMaclaine** [praveenpuglia/css-support#1]
I started making my own version of this project today.  Are you still interested in this idea? Are you interested in working together?

**Comment by praveenpuglia** [comment]
I am interested in the core idea, yes. 

What happened is that I found out https://github.com/mdn/browser-compat-data/ which is a bigger effort and already includes multiple contributors. So instead of duplicating the effort here, it would be best to help that repository grow. Although I thought of slightly different way of handling the prefixed properties or values but it's okay I guess. 

Let me know if there are some use cases where MDN's repository fails and we can talk about that. 

Finally, thanks for showing interest. :)

**Comment by ALMaclaine** [comment]
Thanks for the response, I'm going to look at the repo you linked and other repos and see what functionality is existing and whats missing and I'll let you know if it seems there's an angle that isn't being fully explored.

**Comment by praveenpuglia** [comment]
Sure. 😊 Closing this one for now.
